### ISSUE TITLE
require <filename> gives Error: # of failed Map Tasks exceeded allowed limit.

### ISSUE THREAD

**Issue by sagarlekar** [infochimps-labs/wukong#16] opened 2013-08-08 12:11 UTC
Hello Team Wukong,

I am experimenting with wukong. 
Whenever I use 
require <./lib/facebook.rb> in my wukong script (the file which contains the mapper and reducer processors) I get the 
ERROR streaming.StreamJob: Job not successful. Error: # of failed Map Tasks exceeded allowed limit. FailedCount: 1. LastFailedTask: task_201308081248_0020_m_000000

The script works fine in local mode but not in hadoop mode.

I am using ruby 1.9.3p392, hadoop 1.1.2

I am new to Hadoop and Wukong. Am I doing something obviously wrong?

Kindly help.

Sagar

**Comment by dhruvbansal** [comment] 2013-08-08 19:01
Duplicate of [another issue](https://github.com/infochimps-labs/wukong-hadoop/issues/3).

**Closed as completed by dhruvbansal** 2013-08-08 19:01 UTC
